[supervisord]
nodaemon=true

[program:gunicorn]
command=gunicorn --bind 0.0.0.0:5000 --workers 4 --timeout 300 web.new_web.app:app
autostart=true
autorestart=true
stderr_logfile=/app/logs/gunicorn_err.log
stdout_logfile=/app/logs/gunicorn_out.log

[program:cron]
command=cron -f
autostart=true
autorestart=true
stderr_logfile=/app/logs/cron_err.log
stdout_logfile=/app/logs/cron_out.log
